import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderDoc, RenderError, detectLang } from '../src/render.js';
import { ParseError } from '../src/parse.js';
import { THEMES } from '../src/themes/index.js';

const SRC = `---
title: 测试页
subtitle: 副标题
source: example.org
---
导语 **加粗**。

## A 表格 {span=2 meta="Section 3"}
| 形式 | 状态 |
|---|---|
| 命令式 | ok 已批准 |
| 进行时 | no |

## 原始块
\`\`\`html
<div class="raw-x">raw</div>
\`\`\`
\`\`\`python
print("<x>")
\`\`\`
`;

test('render: outputs a complete single-file HTML with theme attributes and viewport', () => {
  const { html, meta } = renderDoc(SRC);
  assert.match(html, /^<!doctype html>/);
  assert.match(html, /<html lang="zh-CN" data-theme="blueprint" data-mode="auto" data-style="80">/);
  assert.match(html, /name="viewport"/);
  assert.equal(meta.template, 'sheet');
});

test('render: zero external dependencies, no scripts, styles or fonts loaded over http(s)', () => {
  const { html } = renderDoc(SRC);
  assert.doesNotMatch(html, /<script[^>]+src=/);
  assert.doesNotMatch(html, /<link[^>]+href=/);
  assert.doesNotMatch(html, /@import|url\(\s*['"]?https?:/);
});

test('render: flow / sequence SVG styles have fallbacks when the theme context is lost', () => {
  const { html } = renderDoc('## 图\n```flow\nA -> *B: 请求\ngroup 服务: B\n```\n```sequence num\nA -> B: 请求\nnote A, B: 校验\n```');
  // After a previewer extracts the body, html[data-theme] no longer matches. Check every embedded SVG style rule
  // so no variable is missed in highlight, arrow, label, group or shared sequence styles.
  const selectors = [
    '.am-diagram svg', '.am-diagram text', '.am-node-shape',
    '.am-node--hi .am-node-shape', '.am-node--hi text', '.am-edge', '.am-arrow',
    '.am-edge-label rect', '.am-diagram .am-edge-label text', '.am-cluster',
    '.am-diagram .am-cluster-label', '.am-lifeline', '.am-actor', '.am-note',
    '.am-diagram .am-step',
  ];
  const tokens = { ...THEMES.blueprint.common, ...THEMES.blueprint.light };
  for (const selector of selectors) {
    const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const rule = html.match(new RegExp(`${escaped} \\{([^}]+)\\}`))?.[1];
    assert.ok(rule, `${selector} style is embedded`);
    const vars = [...rule.matchAll(/var\(([^)]+)\)/g)];
    assert.ok(vars.length > 0);
    for (const [, value] of vars) {
      assert.match(value, /^--[\w-]+,\s*\S/, `${selector} ${value} needs a fallback`);
      // Color and stroke-width fallbacks are copied from the blueprint light theme; update them here when its tokens change.
      const [name, fallback] = value.split(/,\s*/);
      if (/^[#\d]/.test(fallback)) assert.equal(fallback, tokens[name], `${selector} ${name} fallback must equal the blueprint light token`);
    }
  }
});

test('render: panel ID, title, meta and span take effect', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /id="panel-A" style="grid-column: span 2"/);
  assert.match(html, /<span class="am-panel-meta">Section 3<\/span>/);
  assert.match(html, /<h2>原始块<\/h2>/);
});

test('render: the header has title, subtitle, extra meta and intro', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<h1>测试页<\/h1>/);
  assert.match(html, /am-sub">副标题/);
  assert.match(html, /<b>source<\/b>example.org/);
  assert.match(html, /<strong>加粗<\/strong>/);
});

test('render: status words in tables render as badges', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /am-status--ok"><span class="am-status-icon" aria-hidden="true">✓<\/span>已批准/);
  assert.match(html, /am-status--no/);
  assert.match(html, /am-table-wrap/);
});

test('render: html fences embed as is; unknown languages become escaped code blocks', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<div class="raw-x">raw<\/div>/);
  assert.match(html, /<pre class="am-code"><code data-lang="python">print\(&quot;&lt;x&gt;&quot;\)<\/code><\/pre>/);
});

test('render: the escaped source is embedded in a hidden textarea and reads back unchanged', () => {
  const src = '## A\n```html\n<script>x</script></textarea>\n```';
  const { html } = renderDoc(src);
  const embedded = html.match(/<textarea id="am-source" hidden readonly aria-hidden="true">([\s\S]*?)<\/textarea>/)[1];
  assert.doesNotMatch(embedded, /<\/?(script|textarea)/);
  const unescaped = embedded.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&');
  assert.equal(unescaped, src);
});

test('render: the footer colophon has the version and render time', () => {
  assert.match(renderDoc('## A\nx').html, /<footer class="am-colophon">Generated by Answer me with HTML \d+\.\d+\.\d+ · \d{4}-\d{2}-\d{2} \d{2}:\d{2}<\/footer>/);
});

test('render: CLI overrides take effect and are validated', () => {
  const { html } = renderDoc(SRC, { theme: 'shadcn', template: 'doc' });
  assert.match(html, /data-theme="shadcn"/);
  assert.match(html, /class="am-doc"/);
  assert.throws(() => renderDoc(SRC, { theme: 'x' }), ParseError);
});

test('render: the doc template builds a table of contents with 3 or more panels', () => {
  const { html } = renderDoc('---\ntemplate: doc\n---\n## 一\na\n## 二\nb\n## 三\nc');
  assert.match(html, /<nav class="am-toc"/);
  assert.match(html, /href="#panel-C">C · 三/);
});

test('render: English drafts use English UI labels', () => {
  const { html } = renderDoc('# Hello world\n## A Overview\nThis is a plain English page about things.');
  assert.match(html, /<html lang="en"/);
  assert.match(html, /Copy source/);
});

// Diagrams and the table of contents are named for screen readers in the page's language (#47).
const A11Y_DRAFT = (a, b, c) => `---\ntemplate: doc\n---\n## A ${a}\n\`\`\`flow\nClient -> Server\n\`\`\`\n## B ${b}\n\`\`\`sequence\nClient -> Server: hello\n\`\`\`\n## C ${c}\nx`;

test('render: aria-labels of diagrams and the table of contents follow the page language', () => {
  const en = renderDoc(A11Y_DRAFT('The request path', 'The handshake between them', 'Notes on what happens')).html;
  assert.match(en, /<nav class="am-toc" aria-label="Contents">/);
  assert.match(en, /aria-label="Flowchart: Client, Server"/);
  assert.match(en, /aria-label="Sequence diagram: Client, Server"/);

  const zh = renderDoc(A11Y_DRAFT('请求从客户端发出的路径', '客户端和服务器之间的握手过程', '关于整个过程的补充说明和注意事项')).html;
  assert.match(zh, /<nav class="am-toc" aria-label="目录">/);
  assert.match(zh, /aria-label="流程图：Client、Server"/);
  assert.match(zh, /aria-label="时序图：Client、Server"/);

  const ja = renderDoc(A11Y_DRAFT('クライアントから出るリクエストの流れ', 'クライアントとサーバーのあいだのハンドシェイクの手順', 'この流れについてのほかのメモと注意点')).html;
  assert.match(ja, /<html lang="ja"/);
  assert.match(ja, /<nav class="am-toc" aria-label="目次">/);
  assert.match(ja, /aria-label="フローチャート：Client、Server"/);
  assert.match(ja, /aria-label="シーケンス図：Client、Server"/);
});

test('detectLang: decides by the share of Chinese', () => {
  assert.equal(detectLang('全中文内容'), 'zh');
  assert.equal(detectLang('all english words here'), 'en');
});

test('detectLang: a CJK draft with kana is Japanese', () => {
  assert.equal(detectLang('TCP の3ウェイハンドシェイク'), 'ja');
  assert.equal(detectLang('接続は3回のやりとりで行う'), 'ja');
  assert.equal(detectLang('三次握手建立连接'), 'zh');
  assert.equal(detectLang('a long english sentence with one あ'), 'en');
});

test('render: Japanese drafts use Japanese UI labels and lang="ja"', () => {
  const { html } = renderDoc('# TCP の接続\n## A 概要\n接続は3回のやりとりで行う。');
  assert.match(html, /<html lang="ja"/);
  assert.match(html, /原稿をコピー/);
  assert.match(html, /テーマ：図面/);
  assert.doesNotMatch(html, /复制源稿/);
});

test('render: Japanese pages list Japanese fonts before Chinese fonts', () => {
  const { html } = renderDoc('# TCP の接続\n## A 概要\n接続は3回のやりとりで行う。');
  const rule = html.match(/html\[lang="ja"\]\[data-theme\]\[data-mode\] \{[^}]*\}/)?.[0];
  assert.ok(rule, 'has a Japanese font rule');
  const fonts = rule.match(/--font-sans: ([^;]*);/)[1];
  assert.ok(fonts.indexOf('"Hiragino Sans"') < fonts.indexOf('"PingFang SC"'));
  assert.ok(fonts.indexOf('"Yu Gothic"') < fonts.indexOf('"Microsoft YaHei"'));
});

test('render: counts panels and components', () => {
  const { stats } = renderDoc(SRC);
  assert.equal(stats.panels, 2);
});

test('RenderError: the type exists', () => {
  assert.equal(new RenderError('x', { line: 3 }).line, 3);
});

test('render: the rows attribute spans rows; the bare attribute removes the panel title bar', () => {
  const { html } = renderDoc('## A 高面板 {rows=2 span=2}\nx\n## B {bare}\ny');
  assert.match(html, /id="panel-A" style="grid-column: span 2; grid-row: span 2"/);
  assert.match(html, /<section class="am-panel am-panel--bare" id="panel-B">\n<div class="am-panel-body">/);
});

test('sheet: when the next panel does not fit, the current row is filled with no gap', async () => {
  const { fillRows } = await import('../src/templates/sheet.js');
  const P = (span) => ({ attrs: span ? { span } : {} });
  // cols=2: A(2) | B(1) C(2): C does not fit after B, so B grows to 2
  assert.deepEqual(fillRows([P(2), P(), P(2), P()], 2), [2, 2, 2, 2]);
  // cols=3: A(1) B(1) C(2): A B take 2, C does not fit, B grows to 2; C(2) is the last row and grows to 3
  assert.deepEqual(fillRows([P(), P(), P(2)], 3), [1, 2, 3]);
  // Unchanged when the row is exactly full
  assert.deepEqual(fillRows([P(), P(2), P(3)], 3), [1, 2, 3]);
  // No adjustment when rows spans rows: keep the author's layout
  assert.deepEqual(fillRows([{ attrs: { rows: 2 } }, P(), P(2)], 3), [1, 1, 2]);
});

test('sheet: the automatic widening shows in the rendered output', () => {
  const { html } = renderDoc('---\ncols: 2\n---\n## A {span=2}\nx\n## B\ny\n## C {span=2}\nz');
  assert.match(html, /id="panel-B" style="grid-column: span 2"/);
});

test('detectLang: Chinese quoting one katakana word stays Chinese; a high kana share is Japanese', async () => {
  const { detectLang } = await import('../src/render.js');
  assert.equal(detectLang('这部动画叫《ワンピース》，讲的是海贼的故事，主角想成为海贼王。'), 'zh');
  assert.equal(detectLang('基本的には具体的で効果的な手順を説明します。'), 'ja');
});

test('isJapanese: a short Chinese sentence with only katakana is not Japanese; a short Japanese sentence with hiragana is', async () => {
  const { isJapanese } = await import('../src/svg/text.js');
  assert.equal(isJapanese('我们的项目的《ワンピース》很重要。'), false);
  assert.equal(isJapanese('今日は天気がいいです。'), true);
  assert.equal(isJapanese('東京へ行く。'), true);
});

test('table: headers of right-aligned / centered columns follow align instead of the th default left alignment (#28)', () => {
  const { html } = renderDoc('## A\n| 名 | 数 | 中 |\n| :--- | ---: | :---: |\n| a | 1 | x |\n');
  assert.match(html, /<th align="right">数<\/th>/);
  assert.match(html, /<th align="center">中<\/th>/);
  assert.match(html, /\.am-md th\[align="right"\] \{ text-align: right; \}/);
  assert.match(html, /\.am-md th\[align="center"\] \{ text-align: center; \}/);
});
