// Bundle the CLI into the single file skills/answer-me-with-html/scripts/am.mjs.
// The bundle ships with the skill directory: after npx skills add / a plugin-marketplace install it runs with Node alone, no npm install.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { inlineAssets } from './inline-assets.mjs';

await build({
  entryPoints: [fileURLToPath(new URL('../bin/am.js', import.meta.url))],
  outfile: fileURLToPath(new URL('../skills/answer-me-with-html/scripts/am.mjs', import.meta.url)),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  legalComments: 'eof',
  banner: { js: '// answer-me-with-html CLI — generated by scripts/build.mjs, do not edit. Source: https://github.com/QingYunA/answer-me-with-html' },
  plugins: [inlineAssets],
  logLevel: 'info',
});
